service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'
custom:
  autoswagger:
    typeFiles: [./types/product.d.ts]

# Add the serverless-webpack plugin
plugins:
  - serverless-auto-swagger
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: eu-west-1

  environment:
    SNS_ARN:
      Ref: SNSTopic

  iamRoleStatements:
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic
    - Effect: "Allow"
      Action: "dynamodb:*"
      Resource: "*"

functions:
  getProductsList:
    handler: getProductsList.getProductsList
    environment:
      PRODUCTS_TABLE: products
      STOCKS_TABLE: stocks
    events:
      - http:
          path: products
          method: get
  getProductsById:
    handler: getProductsById.getProductsById
    environment:
      PRODUCTS_TABLE: products
      STOCKS_TABLE: stocks
    events:
      - http:
          path: products/{productId}
          method: get
  createProduct:
    handler: createProduct.createProduct
    environment:
      PRODUCTS_TABLE: products
      STOCKS_TABLE: stocks
    events:
      - http:
          path: products
          method: post
          cors: true
          bodyType: 'Product'
  catalogBatchProcess:
    handler: catalogBatchProcess.catalogBatchProcess
    environment:
      PRODUCTS_TABLE: products
      STOCKS_TABLE: stocks
    events:
      - sqs:
          batchSize: 5
          arn: arn:aws:sqs:eu-west-1:568437974916:catalogItemsQueue

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    stocksTable:
      Type: AWS::DynamoDB::Table
      Properties:      
        TableName: stocks
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        FilterPolicyScope: MessageBody
        FilterPolicy:
          title:
            - Pencil
            - Pen
        Endpoint: ahutsanovich@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    SNSSubscription2:
      Type: AWS::SNS::Subscription
      Properties:
        FilterPolicyScope: MessageBody
        FilterPolicy:
          title:
            - Letter
            - Sharpener
        Endpoint: guts-817@rambler.ru
        Protocol: email
        TopicArn:
          Ref: SNSTopic
