service: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  
  stage: dev
  region: eu-west-1

  environment:
    SQS_URL:
      Ref: SQSQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: upload-csvfiles-bucket
          event: s3:ObjectCreated:*
          rules:
              - prefix: uploaded
          existing: true

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
